// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// - protoc-gen-gorm v0.0.0
// - protoc             v4.25.1
// source: model.proto

package model

import (
	mysqlx "github.com/IguoChan/go-pkg/mysqlx"
	gorm "gorm.io/gorm"
)

// GormModel is an option for User
type UserModel struct {
	Id      int32  `gorm:"primaryKey;column:id" json:"id,omitempty"`
	Name    string `gorm:"column:name" json:"name,omitempty"`
	Address string `gorm:"column:address" json:"address,omitempty"`
	Phone   string `gorm:"column:phone" json:"phone,omitempty"`
}

func (x *UserModel) TableName() string {
	return "user"
}

func UserModelId(x int32) mysqlx.Option {
	return func(db *gorm.DB) *gorm.DB {
		return db.Where("id= ?", x)
	}
}
