// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// - protoc-gen-gorm v
// - protoc          v3.20.3
// source: model.proto

package model

import (
	mysqlx "github.com/IguoChan/go-pkg/mysqlx"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	datatypes "gorm.io/datatypes"
	gorm "gorm.io/gorm"
	time "time"
)

// GormModel is an option for User_Author
type User_AuthorModel struct {
	Name  string `gorm:"column:name" json:"name,omitempty"`
	Email string `gorm:"column:email" json:"email,omitempty"`
}

// GormModel is an option for User
type UserModel struct {
	Id          int32             `gorm:"column:id;type:bigint;primaryKey" json:"id,omitempty"`
	Name        string            `gorm:"column:name;index:idx_name_addr,unique" json:"name,omitempty"`
	Email       string            `gorm:"column:email" json:"email,omitempty"`
	Address     string            `gorm:"column:address;index:idx_name_addr,unique" json:"address,omitempty"`
	Phone       string            `gorm:"column:phone" json:"phone,omitempty"`
	Score       float32           `gorm:"column:score;type:decimal(10,2) unsigned;not null" json:"score,omitempty"`
	Balance     float64           `gorm:"column:balance" json:"balance,omitempty"`
	CreateTime  time.Time         `gorm:"column:create_time;type:datetime;autoCreateTime;not null" json:"create_time,omitempty"`
	UpdateTime  time.Time         `gorm:"column:update_time;type:datetime;autoUpdateTime;not null" json:"update_time,omitempty"`
	DeletedTime gorm.DeletedAt    `gorm:"column:deleted_time;type:datetime;index:idx_deleted_time" json:"deleted_time,omitempty"`
	Date        datatypes.Date    `gorm:"column:date;type:date" json:"date,omitempty"`
	Extra       []byte            `gorm:"column:extra;type:tinyblob;default:'abc'" json:"extra,omitempty"`
	Author      *User_AuthorModel `gorm:"embedded;embeddedPrefix:author_" json:"author,omitempty"`
	Status      string            `gorm:"column:status;type:enum('PENDING','UNKNOWN');default:'UNKNOWN'" json:"status,omitempty"`
	Status1     string            `gorm:"column:status1;default:'UNKNOWN'" json:"status1,omitempty"`
	Status2     Status            `gorm:"column:status2;type:int;default:0" json:"status2,omitempty"`
}

func (x *UserModel) TableName() string {
	return "user"
}

func (x *User) UserModel() *UserModel {
	return &UserModel{}
}

func (x *UserModel) User() *User {
	return &User{}
}

func UserModelId(x int32) mysqlx.Option {
	return func(db *gorm.DB) *gorm.DB {
		return db.Where("id= ?", x)
	}
}

func UserModelName(x string) mysqlx.Option {
	return func(db *gorm.DB) *gorm.DB {
		return db.Where("name= ?", x)
	}
}

func UserModelAddress(x string) mysqlx.Option {
	return func(db *gorm.DB) *gorm.DB {
		return db.Where("address= ?", x)
	}
}

var _ *timestamp.Timestamp
