// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// - protoc-gen-gorm v0.0.0
// - protoc           v3.19.3
// source: model.proto

package model

import (
	context "context"
	sql "database/sql"
	gorm "gorm.io/gorm"
)

type UserDao struct {
	db *gorm.DB
}

func NewUserDao(db *gorm.DB) *UserDao {
	return &UserDao{
		db: db,
	}
}

func (dao *UserDao) Create(ctx context.Context, model *UserModel, opts ...Option) (*UserModel, error) {
	return model, Create(ctx, dao.db, model, opts...)
}

func (dao *UserDao) CreateInBatches(ctx context.Context, models []*UserModel, batchSize int, opts ...Option) ([]*UserModel, error) {
	return models, CreateInBatches(ctx, dao.db, models, batchSize, opts...)
}

func (dao *UserDao) Save(ctx context.Context, model *UserModel, opts ...Option) (*UserModel, error) {
	return model, Save(ctx, dao.db, model, opts...)
}

func (dao *UserDao) First(ctx context.Context, opts ...Option) (*UserModel, error) {
	model := &UserModel{}
	return model, First(ctx, dao.db, model, opts...)
}

func (dao *UserDao) FirstForUpdate(ctx context.Context, opts ...Option) (*UserModel, error) {
	model := &UserModel{}
	return model, FirstForUpdate(ctx, dao.db, model, opts...)
}

func (dao *UserDao) Take(ctx context.Context, opts ...Option) (*UserModel, error) {
	model := &UserModel{}
	return model, Take(ctx, dao.db, model, opts...)
}

func (dao *UserDao) TakeForUpdate(ctx context.Context, opts ...Option) (*UserModel, error) {
	model := &UserModel{}
	return model, TakeForUpdate(ctx, dao.db, model, opts...)
}

func (dao *UserDao) Last(ctx context.Context, opts ...Option) (*UserModel, error) {
	model := &UserModel{}
	return model, Last(ctx, dao.db, model, opts...)
}

func (dao *UserDao) LastForUpdate(ctx context.Context, opts ...Option) (*UserModel, error) {
	model := &UserModel{}
	return model, LastForUpdate(ctx, dao.db, model, opts...)
}

func (dao *UserDao) Find(ctx context.Context, opts ...Option) ([]*UserModel, error) {
	var models []*UserModel
	return models, Find(ctx, dao.db, &models, opts...)
}

func (dao *UserDao) FindForUpdate(ctx context.Context, opts ...Option) ([]*UserModel, error) {
	var models []*UserModel
	return models, FindForUpdate(ctx, dao.db, &models, opts...)
}

func (dao *UserDao) FindInBatches(ctx context.Context, batchSize int, fc func(tx *gorm.DB, batch int) error, opts ...Option) error {
	var models []*UserModel
	return FindInBatches(ctx, dao.db, &models, batchSize, fc, opts...)
}

func (dao *UserDao) FirstOrInit(ctx context.Context, model *UserModel, opts ...Option) (*UserModel, error) {
	return model, FirstOrInit(ctx, dao.db, model, opts...)
}

func (dao *UserDao) FirstOrCreate(ctx context.Context, model *UserModel, opts ...Option) (*UserModel, error) {
	return model, FirstOrCreate(ctx, dao.db, model, opts...)
}

func (dao *UserDao) Update(ctx context.Context, model *UserModel, column string, value interface{}, opts ...Option) (*UserModel, error) {
	return model, Update(ctx, dao.db, model, column, value, opts...)
}

func (dao *UserDao) Updates(ctx context.Context, model *UserModel, values interface{}, opts ...Option) (*UserModel, error) {
	return model, Updates(ctx, dao.db, model, values, opts...)
}

func (dao *UserDao) UpdateColumn(ctx context.Context, model *UserModel, column string, value interface{}, opts ...Option) (*UserModel, error) {
	return model, UpdateColumn(ctx, dao.db, model, column, value, opts...)
}

func (dao *UserDao) UpdateColumns(ctx context.Context, model *UserModel, values interface{}, opts ...Option) (*UserModel, error) {
	return model, UpdateColumns(ctx, dao.db, model, values, opts...)
}

func (dao *UserDao) PartialUpdate(ctx context.Context, model *UserModel, fields map[string]interface{}, opts ...Option) (*UserModel, error) {
	return model, PartialUpdate(ctx, dao.db, model, fields, opts...)
}

func (dao *UserDao) Count(ctx context.Context, opts ...Option) (int64, error) {
	return Count(ctx, dao.db, &UserModel{}, opts...)
}

func (dao *UserDao) Pluck(ctx context.Context, column string, dest interface{}, opts ...Option) error {
	return Pluck(ctx, dao.db, &UserModel{}, column, dest, opts...)
}

func (dao *UserDao) Scan(ctx context.Context, dest interface{}, opts ...Option) error {
	return ScanQuery(ctx, dao.db, dest, opts...)
}

func (dao *UserDao) Delete(ctx context.Context, opts ...Option) error {
	return Delete(ctx, dao.db, &UserModel{}, opts...)
}

func (dao *UserDao) DeleteModel(ctx context.Context, model *UserModel, opts ...Option) error {
	return DeleteModel(ctx, dao.db, model, opts...)
}

func (dao *UserDao) DeleteUnscoped(ctx context.Context, opts ...Option) error {
	return UnscopedDelete(ctx, dao.db, &UserModel{}, opts...)
}

func (dao *UserDao) DeleteModelUnscoped(ctx context.Context, model *UserModel, opts ...Option) error {
	return UnscopedDeleteModel(ctx, dao.db, model, opts...)
}

func (dao *UserDao) Row(ctx context.Context, opts ...Option) *sql.Row {
	return Row(ctx, dao.db, opts...)
}

func (dao *UserDao) Rows(ctx context.Context, opts ...Option) (*sql.Rows, error) {
	return Rows(ctx, dao.db, opts...)
}

func (dao *UserDao) Exec(ctx context.Context, sql string, values ...interface{}) error {
	return Exec(ctx, dao.db, sql, values...)
}

func (dao *UserDao) Transaction(ctx context.Context, fc func(tx *UserDao) error) error {
	return Transaction(ctx, dao.db, func(tx *gorm.DB) error {
		return fc(NewUserDao(tx))
	})
}

type StudentDao struct {
	db *gorm.DB
}

func NewStudentDao(db *gorm.DB) *StudentDao {
	return &StudentDao{
		db: db,
	}
}

func (dao *StudentDao) Create(ctx context.Context, model *StudentModel, opts ...Option) (*StudentModel, error) {
	return model, Create(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) CreateInBatches(ctx context.Context, models []*StudentModel, batchSize int, opts ...Option) ([]*StudentModel, error) {
	return models, CreateInBatches(ctx, dao.db, models, batchSize, opts...)
}

func (dao *StudentDao) Save(ctx context.Context, model *StudentModel, opts ...Option) (*StudentModel, error) {
	return model, Save(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) First(ctx context.Context, opts ...Option) (*StudentModel, error) {
	model := &StudentModel{}
	return model, First(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) FirstForUpdate(ctx context.Context, opts ...Option) (*StudentModel, error) {
	model := &StudentModel{}
	return model, FirstForUpdate(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) Take(ctx context.Context, opts ...Option) (*StudentModel, error) {
	model := &StudentModel{}
	return model, Take(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) TakeForUpdate(ctx context.Context, opts ...Option) (*StudentModel, error) {
	model := &StudentModel{}
	return model, TakeForUpdate(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) Last(ctx context.Context, opts ...Option) (*StudentModel, error) {
	model := &StudentModel{}
	return model, Last(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) LastForUpdate(ctx context.Context, opts ...Option) (*StudentModel, error) {
	model := &StudentModel{}
	return model, LastForUpdate(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) Find(ctx context.Context, opts ...Option) ([]*StudentModel, error) {
	var models []*StudentModel
	return models, Find(ctx, dao.db, &models, opts...)
}

func (dao *StudentDao) FindForUpdate(ctx context.Context, opts ...Option) ([]*StudentModel, error) {
	var models []*StudentModel
	return models, FindForUpdate(ctx, dao.db, &models, opts...)
}

func (dao *StudentDao) FindInBatches(ctx context.Context, batchSize int, fc func(tx *gorm.DB, batch int) error, opts ...Option) error {
	var models []*StudentModel
	return FindInBatches(ctx, dao.db, &models, batchSize, fc, opts...)
}

func (dao *StudentDao) FirstOrInit(ctx context.Context, model *StudentModel, opts ...Option) (*StudentModel, error) {
	return model, FirstOrInit(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) FirstOrCreate(ctx context.Context, model *StudentModel, opts ...Option) (*StudentModel, error) {
	return model, FirstOrCreate(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) Update(ctx context.Context, model *StudentModel, column string, value interface{}, opts ...Option) (*StudentModel, error) {
	return model, Update(ctx, dao.db, model, column, value, opts...)
}

func (dao *StudentDao) Updates(ctx context.Context, model *StudentModel, values interface{}, opts ...Option) (*StudentModel, error) {
	return model, Updates(ctx, dao.db, model, values, opts...)
}

func (dao *StudentDao) UpdateColumn(ctx context.Context, model *StudentModel, column string, value interface{}, opts ...Option) (*StudentModel, error) {
	return model, UpdateColumn(ctx, dao.db, model, column, value, opts...)
}

func (dao *StudentDao) UpdateColumns(ctx context.Context, model *StudentModel, values interface{}, opts ...Option) (*StudentModel, error) {
	return model, UpdateColumns(ctx, dao.db, model, values, opts...)
}

func (dao *StudentDao) PartialUpdate(ctx context.Context, model *StudentModel, fields map[string]interface{}, opts ...Option) (*StudentModel, error) {
	return model, PartialUpdate(ctx, dao.db, model, fields, opts...)
}

func (dao *StudentDao) Count(ctx context.Context, opts ...Option) (int64, error) {
	return Count(ctx, dao.db, &StudentModel{}, opts...)
}

func (dao *StudentDao) Pluck(ctx context.Context, column string, dest interface{}, opts ...Option) error {
	return Pluck(ctx, dao.db, &StudentModel{}, column, dest, opts...)
}

func (dao *StudentDao) Scan(ctx context.Context, dest interface{}, opts ...Option) error {
	return ScanQuery(ctx, dao.db, dest, opts...)
}

func (dao *StudentDao) Delete(ctx context.Context, opts ...Option) error {
	return Delete(ctx, dao.db, &StudentModel{}, opts...)
}

func (dao *StudentDao) DeleteModel(ctx context.Context, model *StudentModel, opts ...Option) error {
	return DeleteModel(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) DeleteUnscoped(ctx context.Context, opts ...Option) error {
	return UnscopedDelete(ctx, dao.db, &StudentModel{}, opts...)
}

func (dao *StudentDao) DeleteModelUnscoped(ctx context.Context, model *StudentModel, opts ...Option) error {
	return UnscopedDeleteModel(ctx, dao.db, model, opts...)
}

func (dao *StudentDao) Row(ctx context.Context, opts ...Option) *sql.Row {
	return Row(ctx, dao.db, opts...)
}

func (dao *StudentDao) Rows(ctx context.Context, opts ...Option) (*sql.Rows, error) {
	return Rows(ctx, dao.db, opts...)
}

func (dao *StudentDao) Exec(ctx context.Context, sql string, values ...interface{}) error {
	return Exec(ctx, dao.db, sql, values...)
}

func (dao *StudentDao) Transaction(ctx context.Context, fc func(tx *StudentDao) error) error {
	return Transaction(ctx, dao.db, func(tx *gorm.DB) error {
		return fc(NewStudentDao(tx))
	})
}
