// Code generated by protoc-gen-gorm. DO NOT EDIT.
// versions:
// - protoc-gen-gorm v0.0.0
// - protoc           v3.19.3
// source: model.proto

package model

import (
	context "context"
	sql "database/sql"
	gorm "gorm.io/gorm"
	clause "gorm.io/gorm/clause"
)

type Option struct {
	apply func(*gorm.DB) *gorm.DB
	isDB  bool
}

func (opt Option) Apply(db *gorm.DB) *gorm.DB {
	if opt.apply == nil {
		return db
	}
	return opt.apply(db)
}

func AutoMigrate(db *gorm.DB, dst ...interface{}) error {
	if db == nil {
		panic("db is nil")
	}
	return db.AutoMigrate(dst...)
}

func DB(db *gorm.DB) Option {
	if db == nil {
		panic("db is nil")
	}
	return Option{
		isDB: true,
		apply: func(*gorm.DB) *gorm.DB {
			return db
		},
	}
}

func Clauses(conds ...clause.Expression) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Clauses(conds...)
		},
	}
}

func Distinct(args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Distinct(args...)
		},
	}
}

func Select(query interface{}, args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Select(query, args...)
		},
	}
}

func Omit(columns ...string) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Omit(columns...)
		},
	}
}

func MapColumns(m map[string]string) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.MapColumns(m)
		},
	}
}

func TableName(name string) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Table(name)
		},
	}
}

func Where(query interface{}, args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Where(query, args...)
		},
	}
}

func Not(query interface{}, args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Not(query, args...)
		},
	}
}

func Or(query interface{}, args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Or(query, args...)
		},
	}
}

func Joins(query string, args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Joins(query, args...)
		},
	}
}

func InnerJoins(query string, args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.InnerJoins(query, args...)
		},
	}
}

func Group(name string) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Group(name)
		},
	}
}

func Having(query interface{}, args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Having(query, args...)
		},
	}
}

func Limit(limit int) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Limit(limit)
		},
	}
}

func Offset(offset int) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Offset(offset)
		},
	}
}

func Order(value interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Order(value)
		},
	}
}

func Scopes(funcs ...func(*gorm.DB) *gorm.DB) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Scopes(funcs...)
		},
	}
}

func Preload(query string, args ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Preload(query, args...)
		},
	}
}

func Attrs(attrs ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Attrs(attrs...)
		},
	}
}

func Assign(attrs ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Assign(attrs...)
		},
	}
}

func Unscoped() Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Unscoped()
		},
	}
}

func Raw(sql string, values ...interface{}) Option {
	return Option{
		apply: func(db *gorm.DB) *gorm.DB {
			return db.Raw(sql, values...)
		},
	}
}

func Create(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Create(model).Error
}

func CreateInBatches(ctx context.Context, db *gorm.DB, models interface{}, batchSize int, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).CreateInBatches(models, batchSize).Error
}

func Save(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Save(model).Error
}

func First(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).First(model).Error
}

func FirstForUpdate(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).First(model, "").Error
}

func Take(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Take(model).Error
}

func TakeForUpdate(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).Take(model, "").Error
}

func Last(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Last(model).Error
}

func LastForUpdate(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).Last(model, "").Error
}

func Find(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Find(model).Error
}

func FindForUpdate(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).Find(model, "").Error
}

func FindInBatches(ctx context.Context, db *gorm.DB, model interface{}, batchSize int, fc func(tx *gorm.DB, batch int) error, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).FindInBatches(model, batchSize, fc).Error
}

func FirstOrInit(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).FirstOrInit(model).Error
}

func FirstOrCreate(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).FirstOrCreate(model).Error
}

func Update(ctx context.Context, db *gorm.DB, model interface{}, column string, value interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Model(model).Update(column, value).Error
}

func Updates(ctx context.Context, db *gorm.DB, model interface{}, values interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Model(model).Updates(values).Error
}

func UpdateColumn(ctx context.Context, db *gorm.DB, model interface{}, column string, value interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Model(model).UpdateColumn(column, value).Error
}

func UpdateColumns(ctx context.Context, db *gorm.DB, model interface{}, values interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Model(model).UpdateColumns(values).Error
}

func PartialUpdate(ctx context.Context, db *gorm.DB, model interface{}, fields map[string]interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Model(model).Updates(fields).Error
}

func Count(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) (int64, error) {
	db = applyOptions(db, opts...)
	var count int64
	return count, db.WithContext(ctx).Model(model).Count(&count).Error
}

func Pluck(ctx context.Context, db *gorm.DB, model interface{}, column string, dest interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Model(model).Pluck(column, dest).Error
}

func ScanQuery(ctx context.Context, db *gorm.DB, dest interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Scan(dest).Error
}

func Delete(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Delete(model).Error
}

func DeleteModel(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	return Delete(ctx, db, model, opts...)
}

func UnscopedDelete(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Unscoped().Delete(model).Error
}

func UnscopedDeleteModel(ctx context.Context, db *gorm.DB, model interface{}, opts ...Option) error {
	return UnscopedDelete(ctx, db, model, opts...)
}

func Row(ctx context.Context, db *gorm.DB, opts ...Option) *sql.Row {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Row()
}

func Rows(ctx context.Context, db *gorm.DB, opts ...Option) (*sql.Rows, error) {
	db = applyOptions(db, opts...)
	return db.WithContext(ctx).Rows()
}

func Exec(ctx context.Context, db *gorm.DB, sql string, values ...interface{}) error {
	return db.WithContext(ctx).Exec(sql, values...).Error
}

func Transaction(ctx context.Context, db *gorm.DB, fc func(tx *gorm.DB) error) error {
	return db.WithContext(ctx).Transaction(fc)
}

func applyOptions(db *gorm.DB, opts ...Option) *gorm.DB {
	for i, opt := range opts {
		if IsDBClosure(opt) {
			opts[i], opts[0] = opts[0], opts[i]
			break
		}
	}

	for _, opt := range opts {
		db = opt.Apply(db)
	}
	return db
}

func IsDBClosure(opt Option) bool {
	return opt.isDB
}
