package protoc_gen_gorm

import (
	"fmt"
	"strconv"
	"strings"
	"unicode"

	"github.com/IguoChan/protoc-gen-gorm/proto/option"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	timePackage   = protogen.GoImportPath("time")
	gormPackage   = protogen.GoImportPath("gorm.io/gorm")
	mysqlxPackage = protogen.GoImportPath("github.com/IguoChan/go-pkg/mysqlx")

	structSuffix = "Model"
)

func GenerateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Messages) == 0 || !existExtension(file.Messages) {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + ".gorm.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-gorm. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-gorm v", "0.0.0")
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()

	g.P("package ", file.GoPackageName)
	g.P()

	for _, m := range file.Messages {
		genMessage(gen, g, m)
		g.P()
	}

	return g
}

func existExtension(msgs []*protogen.Message) bool {
	for _, m := range msgs {
		if proto.HasExtension(m.Desc.Options(), option.E_GormModel) {
			return true
		}
	}

	return false
}

func genMessage(gen *protogen.Plugin, g *protogen.GeneratedFile, m *protogen.Message) {
	if !proto.HasExtension(m.Desc.Options(), option.E_GormModel) {
		return
	}

	g.P("// GormModel is an option for ", m.GoIdent)
	g.P("type ", m.GoIdent, structSuffix, " struct {")
	genMessageFields(g, m)
	g.P("}")
	g.P()

	genTableNameMethod(g, m)
	genIndexFunction(g, m)
}

func genMessageFields(g *protogen.GeneratedFile, m *protogen.Message) {
	for _, field := range m.Fields {
		genMessageField(g, field)
	}
}

type structTags [][2]string

func (tags structTags) String() string {
	if len(tags) == 0 {
		return ""
	}
	var ss []string
	for _, tag := range tags {
		// NOTE: When quoting the value, we need to make sure the backtick
		// character does not appear. Convert all cases to the escaped hex form.
		key := tag[0]
		val := strings.Replace(strconv.Quote(tag[1]), "`", `\x60`, -1)
		ss = append(ss, fmt.Sprintf("%s:%s", key, val))
	}
	return "`" + strings.Join(ss, " ") + "`"
}

func genMessageField(g *protogen.GeneratedFile, field *protogen.Field) {
	if proto.HasExtension(field.Desc.Options(), option.E_IgnoreGormColumn) {
		return
	}

	goType, pointer := fieldGoType(g, field)
	if pointer {
		goType = "*" + goType
	}
	tags := structTags{
		{"gorm", fieldGormTagValue(field)},
		{"json", fieldJSONTagValue(field)},
	}

	name := field.GoName
	g.P(name, " ", goType, tags)
}

func fieldJSONTagValue(field *protogen.Field) string {
	return string(field.Desc.Name()) + ",omitempty"
}

func fieldGormTagValue(field *protogen.Field) string {
	tag := "column:" + camelToSnake(string(field.Desc.Name()))
	if proto.HasExtension(field.Desc.Options(), option.E_PrimaryKey) {
		tag = "primaryKey;" + tag
	}

	return tag
}

func genTableNameMethod(g *protogen.GeneratedFile, m *protogen.Message) {
	g.P("func (x *", m.GoIdent, structSuffix, ") TableName() string {")
	tableName := camelToSnake(m.GoIdent.GoName)
	if proto.HasExtension(m.Desc.Options(), option.E_TableName) {
		tableName = proto.GetExtension(m.Desc.Options(), option.E_TableName).(string)
	}
	g.P("return \"", tableName, "\"")
	g.P("}")
	g.P()
}

func genIndexFunction(g *protogen.GeneratedFile, m *protogen.Message) {
	for _, field := range m.Fields {
		if proto.HasExtension(field.Desc.Options(), option.E_PrimaryKey) {
			genPrimaryKeyFunction(g, m, field)
		}
	}
}

func genPrimaryKeyFunction(g *protogen.GeneratedFile, m *protogen.Message, field *protogen.Field) {
	goType, pointer := fieldGoType(g, field)
	if pointer {
		goType = "*" + goType
	}
	g.P("func ", m.GoIdent, structSuffix, field.GoName, "(x ", goType, ") ", mysqlxPackage.Ident("Option"), " {")
	g.P("return func(db *", gormPackage.Ident("DB"), ") *", gormPackage.Ident("DB"), " {")
	g.P("return db.Where(\"", camelToSnake(field.GoName), "= ?\", x)")
	g.P("}")
	g.P("}")
	g.P()
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

// fieldGoType returns the Go type used for a field.
//
// If it returns pointer=true, the struct field is a pointer to the type.
func fieldGoType(g *protogen.GeneratedFile, field *protogen.Field) (goType string, pointer bool) {
	if field.Desc.IsWeak() {
		return "struct{}", false
	}

	pointer = field.Desc.HasPresence()
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		goType = "bool"
	case protoreflect.EnumKind:
		goType = g.QualifiedGoIdent(field.Enum.GoIdent)
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		goType = "int32"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		goType = "uint32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		goType = "int64"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		goType = "uint64"
	case protoreflect.FloatKind:
		goType = "float32"
	case protoreflect.DoubleKind:
		goType = "float64"
	case protoreflect.StringKind:
		goType = "string"
	case protoreflect.BytesKind:
		goType = "[]byte"
		pointer = false // rely on nullability of slices for presence
	case protoreflect.MessageKind, protoreflect.GroupKind:
		goType = "*" + g.QualifiedGoIdent(field.Message.GoIdent)
		pointer = false // pointer captured as part of the type
	}
	switch {
	case field.Desc.IsList():
		return "[]" + goType, false
	case field.Desc.IsMap():
		keyType, _ := fieldGoType(g, field.Message.Fields[0])
		valType, _ := fieldGoType(g, field.Message.Fields[1])
		return fmt.Sprintf("map[%v]%v", keyType, valType), false
	}
	return goType, pointer
}

func camelToSnake(s string) string {
	var result []rune
	for i, r := range s {
		if unicode.IsUpper(r) {
			// 如果不是第一个字符，前面加下划线
			if i > 0 {
				result = append(result, '_')
			}
			// 转换为小写
			result = append(result, unicode.ToLower(r))
		} else {
			result = append(result, r)
		}
	}
	return string(result)
}
